---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-full.yml
#
http.host: "0"
xpack.monitoring.enabled: false
#xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:29200" ]

## X-Pack security credentials
#
#xpack.monitoring.elasticsearch.username: elastic
#xpack.monitoring.elasticsearch.password: Percon310
